/**
 * A saved camera position and zoom level for quick navigation on the infinite canvas.
 *
 * Bookmarks allow users to save and recall specific viewport positions, making it
 * easy to jump between areas of interest in large drawings. They are stored in the
 * CRDT document and synchronized across collaborators.
 *
 * @property id - Unique identifier generated by {@link generateBookmarkId}
 * @property label - User-visible name displayed in the bookmark panel (e.g. "Title area")
 * @property x - Camera center X coordinate in world space
 * @property y - Camera center Y coordinate in world space
 * @property zoom - Camera zoom level (1.0 = 100%, range ~1e-10 to 1e10)
 * @property createdBy - Client ID of the user who created the bookmark
 * @property createdByName - Display name of the creating user (optional, may be absent for anonymous users)
 * @property createdAt - Unix timestamp (milliseconds) when the bookmark was created
 */
export interface CameraBookmark {
  id: string;
  label: string;
  x: number;
  y: number;
  zoom: number;
  createdBy: string;
  createdByName?: string;
  createdAt: number;
}

let bookmarkCounter = 0;

/**
 * Generates a unique identifier for a new {@link CameraBookmark}.
 *
 * IDs combine the current timestamp with a monotonically increasing counter
 * to ensure uniqueness even when multiple bookmarks are created in rapid
 * succession within the same client.
 *
 * @returns A string in the format `"bookmark-{timestamp}-{counter}"`
 */
export function generateBookmarkId(): string {
  return `bookmark-${Date.now()}-${bookmarkCounter++}`;
}
