/**
 * Maximum allowed image source size stored inline in the CRDT document.
 *
 * Images are persisted as data URI strings, so this limit is measured against
 * the encoded string size rather than decoded pixel bytes.
 */
export const MAX_IMAGE_SOURCE_BYTES = 2 * 1024 * 1024;

/**
 * A raster image placed on the canvas as a first-class drawable item.
 *
 * Images are represented by an inline base64 data URI and positioned in
 * world-space coordinates. They participate in the same timestamp-based
 * rendering order as strokes and shapes.
 *
 * @property id - Unique identifier for this image, generated by {@link generateImageId}.
 * @property src - Base64 data URI (e.g. `"data:image/png;base64,..."`).
 * @property x - Horizontal center position in world-space coordinates.
 * @property y - Vertical center position in world-space coordinates.
 * @property width - Image width in world-space units.
 * @property height - Image height in world-space units, preserving source aspect ratio.
 * @property rotation - Rotation angle in radians, applied around the image center point.
 * @property opacity - Overall image opacity from 0 (fully transparent) to 1 (fully opaque).
 * @property timestamp - Unix timestamp (milliseconds) indicating when the image was created.
 */
export interface CanvasImage {
  id: string;
  src: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  opacity: number;
  timestamp: number;
}

let imageIdCounter = 0;

/**
 * Generates a unique identifier for a new canvas image.
 *
 * IDs are formatted as `"image-{timestamp}-{counter}"` to ensure uniqueness
 * across sessions and within rapid successive calls.
 *
 * @returns A unique string identifier for use as a {@link CanvasImage.id}.
 */
export function generateImageId(): string {
  return `image-${Date.now()}-${imageIdCounter++}`;
}

/**
 * Returns the UTF-8 encoded byte size of an inline image source.
 *
 * This intentionally measures the source string as stored in Yjs, because the
 * CRDT sync payload size is driven by the encoded data URI.
 */
export function getImageSourceSizeBytes(src: string): number {
  return new TextEncoder().encode(src).byteLength;
}

/**
 * Checks whether an inline image source can be stored in the document.
 */
export function isImageSourceWithinLimit(src: string): boolean {
  return getImageSourceSizeBytes(src) <= MAX_IMAGE_SOURCE_BYTES;
}

/**
 * Throws when an inline image source exceeds the CRDT storage limit.
 *
 * Upload UI may resize large files before creating a {@link CanvasImage}; model
 * callers that cannot resize should call this and reject oversized sources.
 */
export function assertImageSourceWithinLimit(src: string): void {
  const size = getImageSourceSizeBytes(src);
  if (size > MAX_IMAGE_SOURCE_BYTES) {
    throw new Error(
      `Image source is ${size} bytes, exceeding the ${MAX_IMAGE_SOURCE_BYTES} byte limit`,
    );
  }
}

/**
 * Creates a canvas image after enforcing the inline source size limit.
 */
export function createCanvasImage(image: CanvasImage): CanvasImage {
  assertImageSourceWithinLimit(image.src);
  return image;
}
