/**
 * The set of geometric shape types supported by the canvas drawing tools.
 *
 * Each shape type corresponds to a tool in the toolbar and determines how the
 * shape's dimensions are interpreted during rendering:
 * - `"rectangle"` — Axis-aligned rectangle defined by width and height.
 * - `"ellipse"` — Ellipse inscribed within the bounding rectangle.
 * - `"polygon"` — Regular polygon with a configurable number of {@link Shape.sides}.
 * - `"star"` — Star shape with configurable {@link Shape.sides} (points) and
 *   {@link Shape.starInnerRadius} ratio.
 */
export type ShapeType = "rectangle" | "ellipse" | "polygon" | "star";

/**
 * A geometric shape placed on the canvas, defined by its bounding rectangle,
 * visual properties, and optional type-specific parameters.
 *
 * Shapes are the second drawing primitive in Drawfinity alongside {@link Stroke}.
 * They are captured via {@link ShapeCapture}, stored in the CRDT document via
 * {@link DrawfinityDoc}, and rendered by the WebGL pipeline. Unlike strokes,
 * shapes are defined by geometric parameters rather than sampled point paths.
 *
 * @property id - Unique identifier for this shape, generated by {@link generateShapeId}.
 * @property type - The geometric shape type, determining how the bounding box is interpreted.
 * @property x - Horizontal center position in world-space coordinates.
 * @property y - Vertical center position in world-space coordinates.
 * @property width - Width of the shape's bounding box in world-space units.
 * @property height - Height of the shape's bounding box in world-space units.
 * @property rotation - Rotation angle in radians, applied around the shape's center point.
 * @property strokeColor - CSS color string (e.g. `"#ff0000"`) for the shape's outline.
 * @property strokeWidth - Width of the shape's outline in world-space units.
 * @property fillColor - CSS color string for the shape's interior fill, or `null` for no fill
 *   (outline only).
 * @property opacity - Overall shape opacity from 0 (fully transparent) to 1 (fully opaque).
 * @property sides - Number of sides for `"polygon"` shapes or number of points for `"star"`
 *   shapes. Optional; only relevant when {@link type} is `"polygon"` or `"star"`.
 * @property starInnerRadius - Ratio (0–1) of the inner radius to the outer radius for star
 *   shapes. A value of 0.5 produces a classic five-pointed star. Optional; only relevant
 *   when {@link type} is `"star"`.
 * @property timestamp - Unix timestamp (milliseconds) indicating when the shape was created.
 *   Used for rendering order — shapes with later timestamps are drawn on top.
 */
export interface Shape {
  id: string;
  type: ShapeType;
  /** Center X in world coordinates */
  x: number;
  /** Center Y in world coordinates */
  y: number;
  width: number;
  height: number;
  /** Rotation in radians */
  rotation: number;
  strokeColor: string;
  strokeWidth: number;
  /** Fill color, or null for no fill */
  fillColor: string | null;
  opacity: number;
  /** Number of sides for polygon/star shapes */
  sides?: number;
  /** Inner radius ratio (0–1) for star shapes */
  starInnerRadius?: number;
  timestamp: number;
}

/**
 * Discriminator type identifying whether a {@link CanvasItem} wraps a stroke or a shape.
 */
export type CanvasItemKind = "stroke" | "shape";

/**
 * A tagged union representing any drawable item on the canvas.
 *
 * Used by APIs that operate on both strokes and shapes uniformly (e.g.
 * {@link DrawfinityDoc.getAllItems}). The `kind` discriminator allows callers
 * to narrow the type and access the appropriate item properties.
 */
export type CanvasItem =
  | { kind: "stroke"; item: import("./Stroke").Stroke }
  | { kind: "shape"; item: Shape };

let shapeIdCounter = 0;

/**
 * Generates a unique identifier for a new shape.
 *
 * IDs are formatted as `"shape-{timestamp}-{counter}"` to ensure uniqueness
 * across sessions and within rapid successive calls.
 *
 * @returns A unique string identifier for use as a {@link Shape.id}.
 */
export function generateShapeId(): string {
  return `shape-${Date.now()}-${shapeIdCounter++}`;
}
