/**
 * A single point within a stroke, representing one sampled position from pointer input.
 *
 * Each point captures the world-space coordinates and stylus/pointer pressure at the
 * moment it was recorded. Points are collected during stroke capture and stored in
 * order to reconstruct the stroke path for rendering.
 *
 * @property x - Horizontal position in world-space coordinates.
 * @property y - Vertical position in world-space coordinates.
 * @property pressure - Normalized pressure value from 0 (no pressure) to 1 (maximum pressure).
 *   For devices without pressure sensitivity (e.g. mouse), this is typically 0.5.
 *   Pressure affects stroke width during rendering via {@link StrokeMesh}.
 */
export interface StrokePoint {
  x: number;
  y: number;
  pressure: number;
}

/**
 * A complete stroke drawn on the canvas, consisting of an ordered sequence of points
 * along with visual properties and metadata.
 *
 * Strokes are the primary drawing primitive in Drawfinity. Each stroke is captured from
 * pointer input via {@link StrokeCapture}, stored in the CRDT document via
 * {@link DrawfinityDoc}, and rendered as triangle-strip geometry by {@link StrokeMesh}.
 *
 * @property id - Unique identifier for this stroke, generated by {@link generateStrokeId}.
 * @property points - Ordered array of {@link StrokePoint} samples captured during drawing.
 *   Must contain at least one point for the stroke to be renderable.
 * @property color - CSS color string (e.g. `"#ff0000"` or `"rgba(255,0,0,0.5)"`) used
 *   to fill the stroke geometry.
 * @property width - Base stroke width in world-space units. The rendered width at each
 *   point is scaled by that point's pressure value.
 * @property opacity - Overall stroke opacity from 0 (fully transparent) to 1 (fully opaque).
 *   Optional; defaults to 1 when not specified. Applied via the brush's `opacityCurve`
 *   during stroke capture.
 * @property timestamp - Unix timestamp (milliseconds) indicating when the stroke was created.
 *   Used for rendering order — strokes with later timestamps are drawn on top.
 */
export interface Stroke {
  id: string;
  points: StrokePoint[];
  color: string;
  width: number;
  opacity?: number;
  timestamp: number;
}

/**
 * Core document model contract for stroke and shape storage.
 *
 * This is the primary abstraction that decouples drawing tools, the renderer, and
 * persistence from any specific storage backend. Both {@link DrawDocument} (in-memory)
 * and {@link DrawfinityDoc} (Yjs CRDT) implement this interface, allowing the
 * application to swap between local-only and collaborative modes transparently.
 *
 * Required methods (`addStroke`, `getStrokes`) cover the minimal stroke lifecycle.
 * Optional methods provide eraser support (`removeStroke`, `replaceStroke`) and
 * shape primitives (`addShape`, `getShapes`, `removeShape`) — implementations may
 * omit these if the feature is not supported.
 *
 * @example
 * ```ts
 * function drawAndRender(doc: DocumentModel, stroke: Stroke, renderer: Renderer) {
 *   doc.addStroke(stroke);
 *   renderer.render(doc.getStrokes());
 * }
 * ```
 */
export interface DocumentModel {
  /** Append a stroke to the document. */
  addStroke(stroke: Stroke): void;
  /** Return all strokes in the document, ordered by insertion time. */
  getStrokes(): Stroke[];
  /**
   * Remove a stroke by its unique ID.
   *
   * @param strokeId - The {@link Stroke.id} to remove.
   * @returns `true` if the stroke was found and removed, `false` otherwise.
   */
  removeStroke?(strokeId: string): boolean;
  /**
   * Atomically remove a stroke and insert zero or more replacements in its place.
   * Used by the eraser tool to split a stroke into segments.
   *
   * @param strokeId - The {@link Stroke.id} of the stroke to replace.
   * @param replacements - New strokes that represent the surviving segments.
   * @returns `true` if the original stroke was found and replaced, `false` otherwise.
   */
  replaceStroke?(strokeId: string, replacements: Stroke[]): boolean;
  /**
   * Add a shape to the document.
   * Optional — only available when shape primitives are supported.
   *
   * @param shape - The shape to add.
   */
  addShape?(shape: import("./Shape").Shape): void;
  /**
   * Return all shapes in the document.
   * Optional — only available when shape primitives are supported.
   */
  getShapes?(): import("./Shape").Shape[];
  /**
   * Remove a shape by its unique ID.
   * Optional — only available when shape primitives are supported.
   *
   * @param shapeId - The shape ID to remove.
   * @returns `true` if the shape was found and removed, `false` otherwise.
   */
  removeShape?(shapeId: string): boolean;
}

let idCounter = 0;

/**
 * Generates a unique identifier for a new stroke.
 *
 * IDs are formatted as `"stroke-{timestamp}-{counter}"` to ensure uniqueness
 * across sessions and within rapid successive calls.
 *
 * @returns A unique string identifier for use as a {@link Stroke.id}.
 */
export function generateStrokeId(): string {
  return `stroke-${Date.now()}-${idCounter++}`;
}
