/**
 * A single point within a stroke, representing one sampled position from pointer input.
 *
 * Each point captures the world-space coordinates and stylus/pointer pressure at the
 * moment it was recorded. Points are collected during stroke capture and stored in
 * order to reconstruct the stroke path for rendering.
 *
 * @property x - Horizontal position in world-space coordinates.
 * @property y - Vertical position in world-space coordinates.
 * @property pressure - Normalized pressure value from 0 (no pressure) to 1 (maximum pressure).
 *   For devices without pressure sensitivity (e.g. mouse), this is typically 0.5.
 *   Pressure affects stroke width during rendering via {@link StrokeMesh}.
 */
export interface StrokePoint {
  x: number;
  y: number;
  pressure: number;
}

/**
 * A complete stroke drawn on the canvas, consisting of an ordered sequence of points
 * along with visual properties and metadata.
 *
 * Strokes are the primary drawing primitive in Drawfinity. Each stroke is captured from
 * pointer input via {@link StrokeCapture}, stored in the CRDT document via
 * {@link DrawfinityDoc}, and rendered as triangle-strip geometry by {@link StrokeMesh}.
 *
 * @property id - Unique identifier for this stroke, generated by {@link generateStrokeId}.
 * @property points - Ordered array of {@link StrokePoint} samples captured during drawing.
 *   Must contain at least one point for the stroke to be renderable.
 * @property color - CSS color string (e.g. `"#ff0000"` or `"rgba(255,0,0,0.5)"`) used
 *   to fill the stroke geometry.
 * @property width - Base stroke width in world-space units. The rendered width at each
 *   point is scaled by that point's pressure value.
 * @property opacity - Overall stroke opacity from 0 (fully transparent) to 1 (fully opaque).
 *   Optional; defaults to 1 when not specified. Applied via the brush's `opacityCurve`
 *   during stroke capture.
 * @property timestamp - Unix timestamp (milliseconds) indicating when the stroke was created.
 *   Used for rendering order — strokes with later timestamps are drawn on top.
 */
export interface Stroke {
  id: string;
  points: StrokePoint[];
  color: string;
  width: number;
  opacity?: number;
  timestamp: number;
}

/** Minimal document interface for stroke storage — implemented by both DrawDocument and DrawfinityDoc. */
export interface DocumentModel {
  addStroke(stroke: Stroke): void;
  getStrokes(): Stroke[];
  removeStroke?(strokeId: string): boolean;
  /** Atomically remove a stroke and insert replacements (for partial erasing). */
  replaceStroke?(strokeId: string, replacements: Stroke[]): boolean;
  /** Returns all shapes in the document (optional — only available when shapes are supported). */
  getShapes?(): import("./Shape").Shape[];
  /** Remove a shape by ID (optional — whole-shape erasure). */
  removeShape?(shapeId: string): boolean;
}

let idCounter = 0;

export function generateStrokeId(): string {
  return `stroke-${Date.now()}-${idCounter++}`;
}
