export type { UserProfile } from "./UserProfile";
export { loadProfile, loadProfileAsync, saveProfile, onProfileChange, USER_COLORS } from "./UserStore";
export type { UserPreferences, GridStyle } from "./UserPreferences";
export { loadPreferences, loadPreferencesAsync, savePreferences } from "./UserPreferences";
export type { UserStats } from "./UserStats";
export { createDefaultStats, loadStats, loadStatsAsync, saveStats, incrementStat, incrementToolUsage } from "./UserStats";
export { StatsTracker } from "./StatsTracker";
export type { BadgeTier, BadgeDefinition } from "./badges";
export { BADGE_CATALOG } from "./badges";
export type { EarnedBadge, BadgeState } from "./badges";
export { loadBadgeState, loadBadgeStateAsync, saveBadgeState } from "./badges";
export type { BadgeUnlockEvent } from "./badges";
export { BadgeEngine } from "./badges";
export type { CanvasRecord, CanvasRecords } from "./CanvasRecords";
export { createDefaultRecords, loadRecords, loadRecordsAsync, saveRecords, updateRecord } from "./CanvasRecords";
